#!/bin/bash

# Pushes image built from Dockerfile to docker hub as 'docknetwork-substrate-builder'.

set -uexo pipefail

# set pwd to the the directory containing this script
cd "$(dirname $0)"

# build the image from ./Dockerfile
docker build -t docknetwork/docknetwork-substrate-builder:latest .

# upload to registry, `docker login` must be run beforehand
docker push docknetwork/docknetwork-substrate-builder:latest
